# Generated by Django 3.2.7 on 2021-09-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Reviews',
        ),
    ]
